---
# tasks file for ansible-molecule-demo

- name: create test file with contents
  copy:
    dest: "{{ test_file }}"
    content: "{{ test_file_content }}"

- name: debug linux distribution info message
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
